# Generated by Django 5.2.3 on 2025-06-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('duration', models.TextField(blank=True, null=True)),
                ('demourl', models.TextField(blank=True, null=True)),
                ('priceaed_android', models.TextField(blank=True, null=True)),
                ('pricedollar_android', models.TextField(blank=True, null=True)),
                ('priceaed_ios', models.TextField(blank=True, null=True)),
                ('pricedollar_ios', models.TextField(blank=True, null=True)),
                ('highlight1', models.TextField(blank=True, null=True)),
                ('highlight2', models.TextField(blank=True, null=True)),
                ('highlight3', models.TextField(blank=True, null=True)),
                ('value1', models.TextField(blank=True, null=True)),
                ('value2', models.TextField(blank=True, null=True)),
                ('value3', models.TextField(blank=True, null=True)),
                ('offering_Identifier', models.TextField(blank=True, null=True)),
                ('package_Identifier', models.TextField(blank=True, null=True)),
                ('entitlement_Identifier', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='course')),
                ('chatroom', models.ImageField(blank=True, null=True, upload_to='course')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
