# Generated by Django 5.2.3 on 2025-06-20 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='duration',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='type',
            new_name='shortdesignation',
        ),
        migrations.AddField(
            model_name='courses',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='trainer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='validity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RegisteredUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('proffesion', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='regsiter')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin.courses')),
            ],
        ),
    ]
