# Generated by Django 5.2.3 on 2025-06-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_trainers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
