# Generated by Django 5.2.3 on 2025-06-21 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_alter_trainers_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='demourl',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='chatroom',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='entitlement_Identifier',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='highlight1',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='highlight2',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='highlight3',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='offering_Identifier',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='package_Identifier',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='priceaed_android',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='priceaed_ios',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='pricedollar_android',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='pricedollar_ios',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='shortdesignation',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='value1',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='value2',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='value3',
        ),
        migrations.AlterField(
            model_name='courses',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin.trainers'),
        ),
    ]
