# Generated by Django 5.2.3 on 2025-06-25 18:06

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_lessions_lessioncontents'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
