# Generated by Django 5.2.3 on 2025-06-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_courses_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredusers',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
